[[redirects]]
from = "/api/*"
to = "http://plantcarehub-001-site1.otempurl.com/:splat"
status = 200

[build]
command = "npm run build"
  publish = "build"  
  base = "/"# Change "build" to your specific publish directory
